// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDtv7bvOolzAe82H6tc65vAwaa2l437LU',
    appId: '1:240442875368:web:39daef072e92dea9d9d85d',
    messagingSenderId: '240442875368',
    projectId: 'whatapp-clone-9f74c',
    authDomain: 'whatapp-clone-9f74c.firebaseapp.com',
    storageBucket: 'whatapp-clone-9f74c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_PcnpxOtTM4JJy_gwt5vLCYuZ1Sn7i9M',
    appId: '1:240442875368:android:fc8cfe2c8ff5bddfd9d85d',
    messagingSenderId: '240442875368',
    projectId: 'whatapp-clone-9f74c',
    storageBucket: 'whatapp-clone-9f74c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP5PfCK7gAmAkJ92BeVuiY8dChEjQKKrs',
    appId: '1:240442875368:ios:08a912e23ac68705d9d85d',
    messagingSenderId: '240442875368',
    projectId: 'whatapp-clone-9f74c',
    storageBucket: 'whatapp-clone-9f74c.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP5PfCK7gAmAkJ92BeVuiY8dChEjQKKrs',
    appId: '1:240442875368:ios:08a912e23ac68705d9d85d',
    messagingSenderId: '240442875368',
    projectId: 'whatapp-clone-9f74c',
    storageBucket: 'whatapp-clone-9f74c.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDtv7bvOolzAe82H6tc65vAwaa2l437LU',
    appId: '1:240442875368:web:de00bc27e30fd3b4d9d85d',
    messagingSenderId: '240442875368',
    projectId: 'whatapp-clone-9f74c',
    authDomain: 'whatapp-clone-9f74c.firebaseapp.com',
    storageBucket: 'whatapp-clone-9f74c.firebasestorage.app',
  );
}
